### ISSUE TITLE
Activity state is not shared while collaboration

### ISSUE THREAD

**Issue by Saumya-Mishra9129** [sugarlabs/imageviewer-activity#32]
Tested collaboration with Ubuntu 20.04 , sucrose version 0.117 .
After joining a shared activity , changes done to image view at sender side, is not visible to joiner and vice versa . (changes here means - normal zoom in-out , rotation of image, full screen view , fit to window and original size) 
Also next image and previous image cannot be seen neither in sender nor at joiner.

**Comment by quozl** [comment]
Yes, that's right.  It is how I expect it should work.  These are not changes to the image data.  Each user has full control over how the shared image is shown, and the image will be in the Journal of each user after the activity is stopped.  I wonder what the use case is for sharing more than the image?  Also, users may have different display resolutions.

**Comment by Saumya-Mishra9129** [comment]
Yeah I was wondering about how collaboration is expected here. Now its cleared that only a image will be share. However sharing multiple images can also be possible, but at this time activity shares only one image. It could be a possible feature of activity. 

> I wonder what the use case is for sharing more than the image? Also, users may have different display resolutions. Also, users may have different display resolutions.

I agree, but like shouldn't we expect collaboration meaning by when sharer will make some changes in image view, joiner will see the changes but sharer will not see changes made by joiner.

**Comment by quozl** [comment]
No, I don't expect changes to how the image is viewed to be shared, because those changes are in the context of the device and display being used.  It would hinder the other users to have their choice of zoom and rotation constrained.

Regarding sharing multiple images ... at the moment, ImageViewer can be started by either opening an image from the Journal to display the image, or opening from the Home View to display all images.  I think the latter method should not share all images over the network; it is unlikely that the child wants to share all their images, and it will take a lot of data transfer to share them all.  The Browse activity only shares bookmarks, not web pages.  The Record activity shares photographs taken within the session, and saves the session metadata as a journal entry.  I suggest that sharing should be prevented when ImageViewer is opened without a specific image selected.
